name: Build Documentation

on: [push, pull_request]

jobs:
    build-documentation:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@master
            with:
                name: dudarboh/LCIO     <-- clone https://github.com/org1/repo1
                
        - name: Setup tmate session
            uses: mxschmitt/action-tmate@v3
