name: Build Documentation

on: [push, pull_request]

jobs:
    build-documentation:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@master
          with:
              repository: dudarboh/LCIO
              path: lcio
        - run: |
            cd lcio/doc
            doxygen Doxyfile
            mv ./html ../../docs/lcio/
            mv DoxyLCIO.tag ../../tags/

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: docs_with_actions  # default: gh-pages

        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3
