name: Build Documentation

on: [push, pull_request]

jobs:
    build-documentation:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout iLCSoftDoc repository
          uses: actions/checkout@master
          with:
              path: iLCSoftDoc
              ref: docs_with_actions

        - name: Checkout LCIO repository
          uses: actions/checkout@master
          with:
              repository: dudarboh/LCIO
              path: lcio

        - name: Create Doxygen documentation and a tag file
          uses: mattnotmitt/doxygen-action@v1.3.1
          with:
              working-directory: 'lcio/doc'
              doxyfile-path: 'Doxyfile'

        - name: Copy documentation to the iLCSoftDoc
          run: |
            cp -r ./lcio/doc/html ./iLCSoftDoc/docs/lcio/
            cp ./lcio/doc/DoxyLCIO.tag ./iLCSoftDoc/tags/

        - name: Push iLCSoftDoc changes
          run: |
              cd ./iLCSoftDoc
              git config --global user.name 'Bohdan Dudar'
              git config --global user.email 'bohdan.dudar@desy.de'
              git add ./*
              git commit -am "Publish LCIO documentation"
              git push

        # - name: Start interactive debug session
        #   uses: mxschmitt/action-tmate@v3
